import Head from 'next/head'

import ControlledAccordions from '../Components/ControlledAccordions'
import Design from '../Components/Dashboard/Design'
import Engineering from '../Components/Dashboard/Engineering'
import Marketing from '../Components/Dashboard/Marketing'
import Navbar from '../Components/Navbar'
import ResponsiveDrawer from '../Components/ResponsiveDrawer'
import ResponsiveDrawerOne from '../Components/ResponsiveDrawerOne'
import ResponsiveDrawerTwo from '../Components/ResponsiveDrawerTwo'
import Sidenav from '../Components/Sidenav'
import SidenavOne from '../Components/SidenavOne'
import SimpleAccordion from '../Components/SimpleAccordion'
import SimpleAccordionOne from '../Components/SimpleAccordionOne'
import SimpleAccordionThree from '../Components/SimpleAccordionThree'
import Subnav from '../Components/Subnav'
import TemporaryDrawer from '../Components/TemporaryDrawer'
import styles from '../styles/Home.module.css'

import { ThemeProvider } from '@material-ui/styles'
import theme from '../Components/theme'


export default function Home() {
  return (
      <ThemeProvider theme={theme}>
      <div className={styles.container}>
      <Head>
        <title>Bildemp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous"></link>
      </Head>

     
       <Sidenav/>
     

      <Navbar/>

      <Subnav/>

      <Engineering/>
      
      <Design/>

      <Marketing/>
    </div>
    </ThemeProvider>
  )
}
